name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: cmbgroundbased/cal/checkout@github_actions
      with:
        submodule_update: ON
    - name: Build the repository
      uses: cmbgroundbased/cal/checkout@github_actions 
