name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: cal/checkout@master
      with:
        submodule_update: ON
    - name: Build the repository
      uses: mkdir build; cd build \
            cmake ../ 
