name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create Build Dir
      run: mkdir build
    - name: run cmake
      run: cd build; cmake ..
    - name: compile
      run:  cd build; make
